### PR TITLE
Fix/put argument remote name

### PR DESCRIPTION
**Pull request by stevokk**
See argument parameters here: https://lftp.yar.ru/lftp-man.html

This may cause a breaking change if people have been using the second parameter as the file name, but should we cater for that?

### CODE REVIEW

**Comment by Atinux** [comment]
Hi @stevokk and thank you for your pull request.

Could you give an example of the new use of it and what exemple will not work anymore due to this change?

**Comment by stevokk** [comment]
@Atinux this isn't a new feature, it just corrects the code to do what the documentation says it should

node-ftps documentation:
`ftps.put(pathToLocalFile, [pathToRemoteFile]) // alias: addFile`
Which correlates to this line in the library (pre-fix):
`return this.raw('put ' + this._escapeshell(localPath) + ' -o ' + this._escapeshell(remotePath));`

So looking at this, the documentation says we can specify a different remote path for the pushed file. But if we check the lftp documentation linked above you will see that "-o" actually sets the filename, and "-O" sets the remote path.

The other way to fix this is to keep the current code and change the documentation to match the code by saying the second parameter is to rename the file when pushing remotely.

**Comment by Atinux** [comment]
I see what you mean, but the `-o` option is more powerful because it let you choose the remote path but also rename the file if needed.

You can do:
`ftps.get('readme.txt', 'my-folder/renamed.txt').exec()` -> Will save the readme.txt file as `renamed.txt` in the `my-folder` folder.

But if you don't want to rename it:
`ftps.get('readme.txt', 'my-folder/').exec()` -> Will save the readme.txt file in the `my-folder` folder without renaming it.

**Comment by stevokk** [comment]
Ah okay, didn't see any mention of moving via the rename flag in the documentation. Thanks

**Comment by Atinux** [comment]
The documentation is not super specific, but thank you for your help to improve node-ftps :)

**Pull request closed without merging**
